# Generated by Django 6.1.1 on 2026-09-27 04:15

import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEntry',
            fields=[
                ('short_id', models.CharField(default=uploader.models.generate_short_id, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
