# Generated by Django 6.1.1 on 2026-09-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageentry',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
